version: 2.1

commands:
  build_capnproto:
    steps:
      - restore_cache:
          key: &capnproto-cache capnproto-cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.MACHINE_OS }}-{{ .Environment.MACHINE_ARCH }}-{{ .Environment.CAPNPROTO_COMMIT }}
      - run:
          name: Check if capnproto already exist
          command: |
            DIR=~/git/capnproto
            if [[ -d "$DIR" ]]
            then
                echo "$DIR exists on your filesystem."
                circleci-agent step halt
            fi
      - run:
          name: Install Capnproto dependency
          command: |
            git clone https://github.com/capnproto/capnproto.git capnproto
            cd capnproto/c++
            git checkout v0.10.2
            git submodule update --init --recursive
            autoreconf -i
            ./configure
            make -j2 # check # skip check for now
            sudo make install
      - save_cache:
          key: *capnproto-cache
          paths:
            - ~/git/capnproto
  build_calibration_tool:
    steps:
      - checkout
      - run:
          name: Install eCAL dependency
          command: |
            sudo add-apt-repository -y ppa:ecal/ecal-5.11
            sudo apt-get update
            sudo apt-get install ecal
      - run:
            name: Update Submodules
            command: git submodule update --init --recursive
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libopencv-dev libglfw3-dev libgtk-3-dev libboost-all-dev libeigen3-dev liblz4-dev bzip2
      - run:
          name: Build calibration_tool
          command: |
              mkdir build
              cd build
              cmake ..
              cmake --build . -j8
              cpack
              mkdir artifacts
              cp *.deb artifacts
      - run:
          name: Run LDD command
          command: |
            cd build
            ldd calibration_tool
      - store_artifacts:
          path: ~/project/build/artifacts

executors:
  ubuntu2204-amd64: &ubuntu2204-amd64-executor
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    working_directory: ~/git
  ubuntu2204-arm64: &ubuntu2204-arm64-executor
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    working_directory: ~/git
  ubuntu2004-amd64: &ubuntu2004-amd64-executor
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    working_directory: ~/git
  ubuntu2004-arm64: &ubuntu2004-arm64-executor
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory: ~/git

workflows:
  ubuntu2004-amd64:
    jobs:
      - build-capnproto:
          os: ubuntu2004-amd64
          context:
            - amd64
            - ubuntu2004
      - build-calibration-tool:
          os: ubuntu2004-amd64
          context:
            - amd64
            - ubuntu2004
          requires:
            - build-capnproto
  ubuntu2204-amd64:
    jobs:
      - build-capnproto:
          os: ubuntu2204-amd64
          context:
            - amd64
            - ubuntu2204
      - build-calibration-tool:
          os: ubuntu2204-amd64
          context:
            - amd64
            - ubuntu2204
          requires:
            - build-capnproto
  ubuntu2004-arm64:
    jobs:
      - build-capnproto:
          os: ubuntu2004-arm64
          context:
            - arm64
            - ubuntu2004
      - build-calibration-tool:
          os: ubuntu2004-arm64
          context:
            - arm64
            - ubuntu2004
          requires:
            - build-capnproto
  ubuntu2204-arm64:
    jobs:
      - build-capnproto:
          os: ubuntu2204-arm64
          context:
            - arm64
            - ubuntu2204
      - build-calibration-tool:
          os: ubuntu2204-arm64
          context:
            - arm64
            - ubuntu2204
          requires:
            - build-capnproto

jobs:
  build-capnproto:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - build_capnproto
  build-calibration-tool:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - build_calibration_tool